
traits<-read.csv("output/Traits.GPS.Comp.26.04.2023c.csv")

traits$above.below.dry.ratio<-as.numeric(paste0(traits$total.below.dry.mass.g))/(traits$total.above.dry.mass.g+as.numeric(paste0(traits$total.below.dry.mass.g)))
traits$cover.area<-pi*(traits$Width.90.cm.y/2)*(traits$Width.long.cm.y/2)
traits$above.volume<-pi*(traits$Width.90.cm.y/2)*(traits$Width.long.cm.y/2)*traits$Height.cm.y*(4/3)
traits$below.volume<-pi*(as.numeric(paste0(traits$Root.lateral.cm))/2)*(as.numeric(paste0(traits$Root.lateral.cm))/2)*as.numeric(paste0(traits$Root.depth.cm))*(4/3)
traits$Root.depth.cm<-as.numeric(paste0(traits$Root.depth.cm))
traits$Root.lateral.cm<-as.numeric(paste0(traits$Root.lateral.cm))
traits$SLA<-as.numeric(paste0(traits$SLA))
traits$Leaf.thickness.mm<-as.numeric(paste0(traits$Leaf.thickness.mm))
traits$Leaf.area.mm2<-as.numeric(paste0(traits$Leaf.area.mm2))
traits$TOTAL_Reproduction<-as.numeric(paste0(traits$TOTAL_Reproduction))

# fits per functional trait below
fit.SLA.2020<-lmer(SLA~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2020),])
fit.SLA.2021<-lmer(SLA~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2021),])
fit.SLA<-lmer(SLA~(1|block)+Year+Native.Exotic*Life.form,traits.sub)
emmeans(fit.SLA, list(pairwise ~ Native.Exotic*Life.form),adjust="tukey")
anova(fit.SLA.2020)
anova(fit.SLA.2021)
anova(fit.SLA)
summary(fit.SLA)
r.squaredGLMM(fit.SLA)


fit.LDMC.2020<-lmer(log(LDMC.dry.wet)~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2020),])
fit.LDMC.2021<-lmer(log(LDMC.dry.wet)~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2021),])
fit.LDMC<-lmer(log(LDMC.dry.wet)~(1|block)+Year+Native.Exotic*Life.form,traits)
anova(fit.LDMC.2020)
anova(fit.LDMC.2021)
anova(fit.LDMC)
summary(fit.LDMC)
emmeans(fit.LDMC, list(pairwise ~ Native.Exotic*Life.form),adjust="tukey")
r.squaredGLMM(fit.LDMC)


fit.Leaf.thickness.mm.2020<-lmer(Leaf.thickness.mm~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2020),])
fit.Leaf.thickness.mm.2021<-lmer(Leaf.thickness.mm~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2021),])
fit.Leaf.thickness<-lmer(Leaf.thickness.mm~(1|block)+Year+Native.Exotic*Life.form,traits)
anova(fit.Leaf.thickness.mm.2020)
anova(fit.Leaf.thickness.mm.2021)
anova(fit.Leaf.thickness)
summary(fit.Leaf.thickness)
emmeans(fit.Leaf.thickness, list(pairwise ~ Native.Exotic*Life.form),adjust="tukey")
r.squaredGLMM(fit.Leaf.thickness)

fit.Leaf.area.mm2.2020<-lmer(log(Leaf.area.mm2)~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2020),])
fit.Leaf.area.mm2.2021<-lmer(log(Leaf.area.mm2)~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2021),])
fit.Leaf.area<-lmer(log(Leaf.area.mm2)~(1|block)+Year+Native.Exotic*Life.form,traits)
anova(fit.Leaf.area.mm2.2020)
anova(fit.Leaf.area.mm2.2021)
anova(fit.Leaf.area)
summary(fit.Leaf.area)
emmeans(fit.Leaf.area, list(pairwise ~ Native.Exotic*Life.form),adjust="tukey")
r.squaredGLMM(fit.Leaf.area)

fit.stem.dry.density.g.mm3.2020<-lmer(stem.dry.density.g.mm3~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2020),])
fit.stem.dry.density.g.mm3.2021<-lmer(stem.dry.density.g.mm3~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2021),])
fit.stem.density.g.mm3<-lmer(stem.dry.density.g.mm3~(1|block)+Year+Native.Exotic*Life.form,traits)
anova(fit.stem.dry.density.g.mm3.2020)
anova(fit.stem.dry.density.g.mm3.2021)
anova(fit.stem.density.g.mm3)
summary(fit.stem.density.g.mm3)
emmeans(fit.stem.density.g.mm3, list(pairwise ~ Native.Exotic*Life.form),adjust="tukey")
r.squaredGLMM(fit.stem.density.g.mm3)

fit.root.dry.density.g.mm3.2020<-lmer(root.dry.density.g.mm3~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2020),])
fit.root.dry.density.g.mm3.2021<-lmer(root.dry.density.g.mm3~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2021),])
fit.root.density.g.mm3<-lmer(root.dry.density.g.mm3~(1|block)+Year+Native.Exotic*Life.form,traits)
anova(fit.root.dry.density.g.mm3.2020)
anova(fit.root.dry.density.g.mm3.2021)
anova(fit.root.density.g.mm3)
summary(fit.root.density.g.mm3)
emmeans(fit.root.density.g.mm3, list(pairwise ~ Native.Exotic*Life.form),adjust="tukey")
r.squaredGLMM(fit.root.density.g.mm3)

fit.above.volume.2020<-lmer(log(above.volume)~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2020),])
fit.above.volume.2021<-lmer(log(above.volume)~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2021),])
fit.above.volume<-lmer(log(above.volume)~(1|block)+Year+Native.Exotic*Life.form,traits)
anova(fit.above.volume.2020)
anova(fit.above.volume.2021)
anova(fit.above.volume)
summary(fit.above.volume)
emmeans(fit.above.volume, list(pairwise ~ Native.Exotic*Life.form),adjust="tukey")
r.squaredGLMM(fit.above.volume)

fit.below.volume.2020<-lmer(log(below.volume)~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2020),])
fit.below.volume.2021<-lmer(log(below.volume)~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2021),])
fit.below.volume<-lmer(log(below.volume)~(1|block)+Year+Native.Exotic*Life.form,traits)
anova(fit.below.volume.2020)
anova(fit.below.volume.2021)
anova(fit.below.volume)
summary(fit.below.volume)
emmeans(fit.below.volume, list(pairwise ~ Native.Exotic*Life.form),adjust="tukey")
r.squaredGLMM(fit.below.volume)

fit.above.below.dry.ratio.2020<-lmer(above.below.dry.ratio~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2020),])
fit.above.below.dry.ratio.2021<-lmer(above.below.dry.ratio~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2021),])
fit.RMF<-lmer(above.below.dry.ratio~(1|block)+Year+Native.Exotic*Life.form,traits)
anova(fit.above.below.dry.ratio.2020)
anova(fit.above.below.dry.ratio.2021)
anova(fit.RMF)
summary(fit.RMF)
emmeans(fit.RMF, list(pairwise ~ Native.Exotic*Life.form),adjust="tukey")
r.squaredGLMM(fit.RMF)


fit.TOTAL_Reproduction.2020<-lmer(log(TOTAL_Reproduction+1)~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2020),])
fit.TOTAL_Reproduction.2021<-lmer(log(TOTAL_Reproduction+1)~(1|block)+Native.Exotic*Life.form,traits[which(traits$Year==2021),])
fit.TOTAL<-lmer(log(TOTAL_Reproduction+1)~(1|block)+Year+Native.Exotic*Life.form,traits)
anova(fit.TOTAL_Reproduction.2020)
anova(fit.TOTAL_Reproduction.2021)
anova(fit.TOTAL)
summary(fit.TOTAL)
emmeans(fit.TOTAL, list(pairwise ~ Native.Exotic*Life.form),adjust="tukey")
r.squaredGLMM(fit.TOTAL)

rm(traits)